services:
  access-control-app:
    build:
        context: .
    container_name: access-control-app
    ports:
      - ${FLASK_AC_APP_PORT}:${FLASK_AC_APP_PORT}
    environment:
      - FLASK_AC_APP_HOST=${FLASK_AC_APP_HOST}
      - FLASK_AC_APP_PORT=${FLASK_AC_APP_PORT}
      - FLASK_AC_APP_NAME=${FLASK_AC_APP_NAME}
      - FLASK_AC_APP_DEBUG=${FLASK_AC_APP_DEBUG}
      - FLASK_AC_APP_ENV=${FLASK_AC_APP_ENV}
      - FLASK_AC_APP_SECRET_KEY=${FLASK_AC_APP_SECRET_KEY}
      - FLASK_AC_APP_DATABASE_URI=${FLASK_AC_APP_DATABASE_URI}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - OIDC_OP_AUTHORIZATION_ENDPOINT=${OIDC_OP_AUTHORIZATION_ENDPOINT}
      - OIDC_OP_ENDSESSION_ENDPOINT=${OIDC_OP_ENDSESSION_ENDPOINT}
      - OIDC_OP_JWKS_ENDPOINT=${OIDC_OP_JWKS_ENDPOINT}
      - OIDC_OP_LOGOUT_ENDPOINT=${OIDC_OP_LOGOUT_ENDPOINT}
      - OIDC_OP_LOGOUT_URL_METHOD=${OIDC_OP_LOGOUT_URL_METHOD}
      - OIDC_OP_TOKEN_ENDPOINT=${OIDC_OP_TOKEN_ENDPOINT}
      - OIDC_OP_USER_ENDPOINT=${OIDC_OP_USER_ENDPOINT}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - OIDC_RP_REALM_ID=${OIDC_RP_REALM_ID}
      - OIDC_RP_CLIENT_SECRET=${OIDC_RP_CLIENT_SECRET}
      - OIDC_RP_SIGN_ALGO=${OIDC_RP_SIGN_ALGO}
    command: python app.py
    volumes:
      - .:/app